# Site settings
title: SmallK
email: your-email@domain.com
description: "SmallK"
baseurl: ""
url: "https://smallk.github.io"
githubproject: "https://github.com/smallk"

# Build settings
markdown: kramdown
permalink: pretty

source: pages
include: pages
exclude: README.md