# Site settings
title: Smallk
email: your-email@domain.com
description: "Smallk"
baseurl: ""
url: "https://smallk.github.io"
githubproject: "https://github.com/smallk"

# Build settings
markdown: kramdown
permalink: pretty
